void main(){
  print("welcome to ooty ");
  try {
    int div = 20 ~/ 0;
  }
  catch(obj){
    print("Exception occured : $obj");
  }
  print("thank you");


  // nice to meet u wont print cause there is an exception

}